#!/bin/bash

if [ $# = 0 ]
then echo "I'v done nothing"; exit;fi
if [[ $1 == ? ]] || [[ $2 == '' ]] || [[ $3 == '' ]]
then echo "Use: ./script [prefix] [range start] [range end]";exit;fi
if [[ $1 == '-i' ]]
then i=1; shift
else i=0;fi
echo "i=$i \$1=$1 \$#=$# \$2=$2 \$3=$3"
k2=$2; k3=$3
if [ $# = 0 ];then
for file in *
do
echo "do delete file $file ? (y,n)"
read a 
size=$(wc -c $file | awk '{print $1}')
if [[ $a == 'y' ]] && [[ $size -ge $k2 ]] && [[ $size -le $k3 ]];then 
rm $file;fi
done
else
for file in $1*;do
size=$(wc -c $file | awk '{print $1}')
if [ $i = 1 ]
then
echo "do delete file $file ? (y,n)"
read a 
if [[ $a == 'y' ]] && [[ $size -ge $k2 ]] && [[ $size -le $k3 ]];then 
rm $file;fi
else
echo "size=$size  k2=$k2  k3=$k3"
if [[ $size -ge $k2 ]] && [[ $size -le $k3 ]];then 
rm $file
echo $file deleted; fi
fi
done
fi
